/**
 * Mobile Market Dashboard — RWA Protocol Directory
 *
 * COMPLIANCE: Displays only publicly available DeFiLlama data (TVL, chains,
 * asset class). No platform-generated scores, ratings, tiers, or risk grades.
 */
import { useState } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
} from 'react-native';
import { MaterialIcons } from '@expo/vector-icons';
import { colors } from '../constants/theme';

// Sample data — in production sourced from /data/leaderboard.json (DeFiLlama)
const assets = [
  {
    id: 1,
    icon: 'payments' as const,
    name: 'BlackRock BUIDL',
    ticker: 'BUIDL',
    class: 'Gov. Treasuries',
    tvl: '$1.24B',
    change1d: '+0.12%',
    chains: 'Ethereum, Polygon',
    audits: 2,
    url: 'https://www.blackrock.com',
  },
  {
    id: 2,
    icon: 'foundation' as const,
    name: 'Ondo USDY',
    ticker: 'USDY',
    class: 'Gov. Treasuries',
    tvl: '$540M',
    change1d: '+0.04%',
    chains: 'Ethereum, Solana',
    audits: 3,
    url: 'https://ondo.finance',
  },
  {
    id: 3,
    icon: 'factory' as const,
    name: 'Maple Finance',
    ticker: 'MPL',
    class: 'Private Credit',
    tvl: '$188M',
    change1d: '-0.31%',
    chains: 'Ethereum, Solana',
    audits: 5,
    url: 'https://maple.finance',
  },
  {
    id: 4,
    icon: 'eco' as const,
    name: 'Paxos Gold',
    ticker: 'PAXG',
    class: 'Precious Metal',
    tvl: '$612M',
    change1d: '+0.88%',
    chains: 'Ethereum',
    audits: 4,
    url: 'https://paxos.com',
  },
];

const LAYER_NAMES = [
  'Legal & Regulatory',
  'Valuation & Transparency',
  'Custody & Security',
  'KYC / Counterparty',
  'Liquidity & Market',
  'Settlement & Ops',
];

export default function MarketDashboard() {
  const [selected, setSelected] = useState(assets[0]);
  const [tab, setTab] = useState<'table' | 'detail'>('table');

  return (
    <View style={styles.container}>
      {/* Disclaimer banner */}
      <View style={styles.disclaimerBar}>
        <MaterialIcons name="info-outline" size={12} color={colors.primary} />
        <Text style={styles.disclaimerText}>
          Data: DeFiLlama · Research tool only · Not a rating service
        </Text>
      </View>

      {/* Tab Toggle */}
      <View style={styles.tabBar}>
        {(['table', 'detail'] as const).map((t) => (
          <TouchableOpacity
            key={t}
            style={[styles.tabBtn, tab === t && styles.tabBtnActive]}
            onPress={() => setTab(t)}
          >
            <Text style={[styles.tabLabel, tab === t && styles.tabLabelActive]}>
              {t === 'table' ? 'Protocol Directory' : `Detail: ${selected.name.split(' ')[0]}`}
            </Text>
          </TouchableOpacity>
        ))}
      </View>

      {tab === 'table' ? (
        <ScrollView style={styles.scroll}>
          <View style={styles.pageHeader}>
            <Text style={styles.pageTitle}>RWA Protocol Directory</Text>
            <Text style={styles.pageSubtitle}>
              Public market data for tokenized real-world asset protocols.
              No scores or ratings are generated by this platform.
            </Text>
          </View>
          {assets.map((asset) => (
            <TouchableOpacity
              key={asset.id}
              style={[styles.assetRow, selected.id === asset.id && styles.assetRowSelected]}
              onPress={() => { setSelected(asset); setTab('detail'); }}
              activeOpacity={0.7}
            >
              <View style={styles.assetLeft}>
                <View style={styles.assetIcon}>
                  <MaterialIcons name={asset.icon} size={18} color={colors.primary} />
                </View>
                <View>
                  <Text style={styles.assetName}>{asset.name}</Text>
                  <Text style={styles.assetTicker}>{asset.ticker} · {asset.class}</Text>
                </View>
              </View>
              <View style={styles.assetRight}>
                <Text style={styles.tvlValue}>{asset.tvl}</Text>
                <Text style={[
                  styles.changeValue,
                  { color: asset.change1d.startsWith('+') ? colors.green : colors.error }
                ]}>
                  {asset.change1d}
                </Text>
              </View>
            </TouchableOpacity>
          ))}
        </ScrollView>
      ) : (
        <ScrollView style={styles.scroll}>
          {/* Protocol header */}
          <View style={styles.detailHeader}>
            <Text style={styles.detailLabel}>PROTOCOL DETAIL</Text>
            <Text style={styles.detailTitle}>{selected.name}</Text>
            <Text style={styles.detailClass}>{selected.class}</Text>
            <View style={styles.detailStats}>
              <View style={styles.detailStat}>
                <Text style={styles.statLabel}>TVL</Text>
                <Text style={styles.statValue}>{selected.tvl}</Text>
              </View>
              <View style={styles.detailStat}>
                <Text style={styles.statLabel}>24h Change</Text>
                <Text style={[
                  styles.statValue,
                  { color: selected.change1d.startsWith('+') ? colors.green : colors.error }
                ]}>
                  {selected.change1d}
                </Text>
              </View>
              <View style={styles.detailStat}>
                <Text style={styles.statLabel}>Audits</Text>
                <Text style={styles.statValue}>{selected.audits}</Text>
              </View>
            </View>
          </View>

          {/* Public info */}
          <View style={styles.detailBody}>
            <Text style={styles.sectionLabel}>Public Information</Text>
            <InfoRow label="Chains" value={selected.chains} />
            <InfoRow label="Asset Class" value={selected.class} />
            <InfoRow label="Official URL" value={selected.url} />
          </View>

          {/* RARM layer names (educational) */}
          <View style={styles.detailBody}>
            <Text style={styles.sectionLabel}>RARM Framework Dimensions</Text>
            <Text style={styles.educationalNote}>
              Use the RARM due diligence workbook (web app, login required) to apply these
              six dimensions to your own analysis of this protocol.
            </Text>
            {LAYER_NAMES.map((name, i) => (
              <View key={i} style={styles.layerRow}>
                <Text style={styles.layerNum}>L{i + 1}</Text>
                <Text style={styles.layerLabel}>{name}</Text>
              </View>
            ))}
          </View>

          {/* Data attribution */}
          <View style={styles.attributionPanel}>
            <Text style={styles.attributionText}>
              Market data sourced from DeFiLlama (api.llama.fi). RWAscope does not provide
              credit ratings, investment advice, or any regulated financial service. This
              data is for research purposes only.
            </Text>
          </View>

          <View style={{ height: 40 }} />
        </ScrollView>
      )}
    </View>
  );
}

function InfoRow({ label, value }: { label: string; value: string }) {
  return (
    <View style={infoStyles.row}>
      <Text style={infoStyles.label}>{label}</Text>
      <Text style={infoStyles.value}>{value}</Text>
    </View>
  );
}

const infoStyles = StyleSheet.create({
  row: { flexDirection: 'row', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: colors.outlineVariant + '20' },
  label: { width: 90, fontSize: 11, fontWeight: '700', color: colors.outline, textTransform: 'uppercase' },
  value: { flex: 1, fontSize: 12, color: colors.onSurface },
});

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.surface },
  scroll: { flex: 1 },
  disclaimerBar: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 16, paddingVertical: 6, backgroundColor: colors.surfaceContainerLow, borderBottomWidth: 1, borderBottomColor: colors.outlineVariant + '20' },
  disclaimerText: { fontSize: 10, color: colors.onSurfaceVariant, flex: 1 },
  tabBar: { flexDirection: 'row', backgroundColor: colors.surfaceContainerLow, borderBottomWidth: 1, borderBottomColor: colors.outlineVariant + '30' },
  tabBtn: { flex: 1, paddingVertical: 12, alignItems: 'center' },
  tabBtnActive: { borderBottomWidth: 2, borderBottomColor: colors.primary },
  tabLabel: { fontSize: 11, fontWeight: '700', color: colors.outline, textTransform: 'uppercase', letterSpacing: 0.5 },
  tabLabelActive: { color: colors.primary },
  pageHeader: { padding: 20, borderBottomWidth: 1, borderBottomColor: colors.outlineVariant + '20' },
  pageTitle: { fontSize: 24, fontWeight: '800', color: colors.onSurface, letterSpacing: -0.5 },
  pageSubtitle: { fontSize: 12, color: colors.onSurfaceVariant, marginTop: 4, lineHeight: 18 },
  assetRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: colors.outlineVariant + '15', backgroundColor: colors.surfaceContainerLowest },
  assetRowSelected: { backgroundColor: colors.surfaceContainerHigh },
  assetLeft: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  assetIcon: { width: 36, height: 36, backgroundColor: colors.surfaceContainer, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.outlineVariant + '30' },
  assetName: { fontSize: 13, fontWeight: '700', color: colors.onSurface },
  assetTicker: { fontSize: 10, color: colors.onSurfaceVariant, marginTop: 1 },
  assetRight: { alignItems: 'flex-end', gap: 2 },
  tvlValue: { fontSize: 14, fontWeight: '700', color: colors.onSurface },
  changeValue: { fontSize: 10, fontWeight: '600' },
  detailHeader: { padding: 20, borderBottomWidth: 1, borderBottomColor: colors.outlineVariant + '20', backgroundColor: colors.surfaceContainerLowest },
  detailLabel: { fontSize: 10, fontWeight: '700', color: colors.primary, letterSpacing: 1.5, textTransform: 'uppercase' },
  detailTitle: { fontSize: 22, fontWeight: '800', color: colors.onSurface, marginTop: 4 },
  detailClass: { fontSize: 12, color: colors.onSurfaceVariant, marginTop: 2 },
  detailStats: { flexDirection: 'row', marginTop: 16, gap: 16 },
  detailStat: {},
  statLabel: { fontSize: 9, fontWeight: '700', color: colors.onSurfaceVariant, textTransform: 'uppercase', marginBottom: 2 },
  statValue: { fontSize: 16, fontWeight: '700' },
  detailBody: { padding: 20 },
  sectionLabel: { fontSize: 10, fontWeight: '700', color: colors.onSurfaceVariant, textTransform: 'uppercase', letterSpacing: 1.5, marginBottom: 12 },
  educationalNote: { fontSize: 12, color: colors.onSurfaceVariant, lineHeight: 18, marginBottom: 12 },
  layerRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: colors.outlineVariant + '15' },
  layerNum: { fontSize: 10, fontWeight: '700', color: colors.primary, width: 24 },
  layerLabel: { fontSize: 13, fontWeight: '600', color: colors.onSurface },
  attributionPanel: { backgroundColor: colors.surfaceContainerLowest, padding: 16, margin: 16, borderLeftWidth: 3, borderLeftColor: colors.outlineVariant + '40' },
  attributionText: { fontSize: 11, color: colors.onSurfaceVariant, lineHeight: 17 },
});
