import { test, expect } from '@playwright/test';

/**
 * Self-Assessment page tests.
 *
 * After compliance refactoring (Commit 2) the /self-assessment route shows
 * an educational framework overview only. There is no interactive scoring
 * tool, no computed confidence %, and no tier/risk-grade output.
 */
test.describe('RARM Framework Overview (/self-assessment)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/self-assessment');
    await page.setViewportSize({ width: 1440, height: 900 });
  });

  // ── Page identity ──────────────────────────────────────────────────────────
  test('renders hero title "RARM Framework Overview"', async ({ page }) => {
    await expect(page.getByRole('heading', { name: /RARM Framework Overview/i })).toBeVisible();
  });

  test('shows "Academic Research Tool" badge', async ({ page }) => {
    await expect(page.getByText(/Academic Research Tool/i).first()).toBeVisible();
  });

  test('shows description mentioning "academic methodology"', async ({ page }) => {
    await expect(page.getByText(/academic methodology/i)).toBeVisible();
  });

  // ── Compliance: no scores or tiers ────────────────────────────────────────
  test('does NOT show Global Confidence panel', async ({ page }) => {
    await expect(page.getByText('Global Confidence')).toHaveCount(0);
  });

  test('does NOT show Risk Profile / tier output', async ({ page }) => {
    await expect(page.getByText('Risk Profile')).toHaveCount(0);
    await expect(page.getByText(/Tier [1-4]/)).toHaveCount(0);
  });

  test('does NOT show L1 STRUCTURAL WARNING auto-generated by platform', async ({ page }) => {
    await expect(page.getByText('L1 STRUCTURAL WARNING')).toHaveCount(0);
  });

  test('does NOT have a "Calculate Score" button', async ({ page }) => {
    await expect(page.getByRole('button', { name: /calculate score/i })).toHaveCount(0);
  });

  test('does NOT have score sliders (not an interactive tool)', async ({ page }) => {
    await expect(page.locator('input[type="range"]')).toHaveCount(0);
  });

  // ── Educational content ────────────────────────────────────────────────────
  test('renders all 6 RARM layer cards', async ({ page }) => {
    for (let i = 1; i <= 6; i++) {
      await expect(page.getByText(new RegExp(`Layer 0?${i}`, 'i')).first()).toBeVisible();
    }
  });

  test('shows RARM Reference section with methodology link', async ({ page }) => {
    await expect(page.getByText(/RARM Reference/i)).toBeVisible();
    await expect(page.getByRole('link', { name: /methodology/i })).toBeVisible();
  });

  test('shows CTA to create account or open due diligence tool', async ({ page }) => {
    // For unauthenticated user: should show Create Account / Learn Framework CTAs
    await expect(
      page.getByRole('button', { name: /Create Free Account|Open Due Diligence Tool/i })
    ).toBeVisible();
  });

  test('has disclaimer mentioning "not a rating service"', async ({ page }) => {
    await expect(page.getByText(/does not generate.*ratings|not.*rating/i).first()).toBeVisible();
  });
});
