"""0013 add tokenized assets tables

Revision ID: 0859dd8457ff
Revises: 0012
Create Date: 2026-05-29 13:30:27.766214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0859dd8457ff'
down_revision: Union[str, None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenized_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('cmc_rank', sa.Integer(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('market_cap_usd', sa.Float(), nullable=True),
    sa.Column('volume_24h_usd', sa.Float(), nullable=True),
    sa.Column('percent_change_1h', sa.Float(), nullable=True),
    sa.Column('percent_change_24h', sa.Float(), nullable=True),
    sa.Column('percent_change_7d', sa.Float(), nullable=True),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tokenized_assets_cat_mcap', 'tokenized_assets', ['category', 'market_cap_usd'], unique=False)
    op.create_index(op.f('ix_tokenized_assets_category'), 'tokenized_assets', ['category'], unique=False)
    op.create_table('tokenized_category_summary',
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('cmc_category_id', sa.String(), nullable=False),
    sa.Column('cmc_category_name', sa.String(), nullable=False),
    sa.Column('num_tokens', sa.Integer(), nullable=True),
    sa.Column('market_cap_usd', sa.Float(), nullable=True),
    sa.Column('avg_price_change_24h', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('category')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokenized_category_summary')
    op.drop_index(op.f('ix_tokenized_assets_category'), table_name='tokenized_assets')
    op.drop_index('ix_tokenized_assets_cat_mcap', table_name='tokenized_assets')
    op.drop_table('tokenized_assets')
    # ### end Alembic commands ###
